# Generated by Django 4.1.5 on 2023-01-16 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokenUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True, verbose_name='Отказавший узел')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Отказавший узел',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='Имя')),
                ('factory_number', models.CharField(max_length=24, unique=True, verbose_name='Заводской номер')),
                ('engine_number', models.CharField(max_length=24, verbose_name='Номер двигателя')),
                ('transmission_number', models.CharField(max_length=24, verbose_name='Номер трансмиссии')),
                ('drive_axle_number', models.CharField(max_length=24, verbose_name='Номер ведущего моста')),
                ('steerable_axle_number', models.CharField(max_length=24, verbose_name='Номер управляемого моста')),
                ('supply_contract', models.CharField(max_length=24, verbose_name='Договор поставки №, дата.')),
                ('date_of_shipment_from_the', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('consignee', models.CharField(max_length=24, verbose_name='Грузополучатель')),
                ('delivery_address', models.CharField(max_length=150, verbose_name='Адрес поставки (эксплуатации)')),
                ('equipment', models.CharField(max_length=150, verbose_name='Комплектация (доп. опции)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='CarComplaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Машина-рекламации',
            },
        ),
        migrations.CreateModel(
            name='DriveAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True, verbose_name='Модель ведущего моста')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель ведущего моста',
            },
        ),
        migrations.CreateModel(
            name='EngineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True, verbose_name='Модель двигателя')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель двигателя',
            },
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124, verbose_name='Способ восстановления')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Способ восстановления',
            },
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True, verbose_name='Сервисная компания')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Сервисная компания',
            },
        ),
        migrations.CreateModel(
            name='SteerableAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True, verbose_name='Модель управляемого моста')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель управляемого моста',
            },
        ),
        migrations.CreateModel(
            name='TechniqueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True, verbose_name='Модель техники')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель техники',
            },
        ),
        migrations.CreateModel(
            name='TransmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True, verbose_name='Модель трансмиссии')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель трансмиссии',
            },
        ),
        migrations.CreateModel(
            name='TypeOfMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True, verbose_name='Тип ТО')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип ТО',
            },
        ),
        migrations.CreateModel(
            name='TechnicalMintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='Имя')),
                ('date_of_maintenance', models.DateField(verbose_name='Дата проведения ТО')),
                ('оperating_time', models.IntegerField(verbose_name='Наработка, м/час')),
                ('order', models.CharField(max_length=24, verbose_name='№ заказ-наряда')),
                ('date_of_the_order', models.DateField(verbose_name='Дата заказ-наряда')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.car', verbose_name='Mашина')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.servicecompany', verbose_name='Сервисная компания')),
                ('type_of_maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.typeofmaintenance', verbose_name='Тип ТО')),
            ],
            options={
                'verbose_name': 'Техническое обслуживание (ТО)',
            },
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='Имя')),
                ('date_of_breakdown', models.DateTimeField(verbose_name='Дата отказа')),
                ('оperating_time', models.IntegerField(verbose_name='Наработка, м/час')),
                ('breakdown_description', models.TextField(verbose_name='Описание отказа')),
                ('spare_parts', models.TextField(max_length=200, verbose_name='Используемые запасные части')),
                ('date_restoration', models.DateTimeField(verbose_name='Дата восстановления')),
                ('broken_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.brokenunit', verbose_name='Узел отказа')),
                ('car', models.ManyToManyField(through='silant.CarComplaints', to='silant.car', verbose_name='Mашина')),
                ('recovery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.recoverymethod', verbose_name='Способ восстановления')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.servicecompany', verbose_name='Сервисная компания')),
            ],
            options={
                'verbose_name': 'Рекламации',
            },
        ),
        migrations.AddField(
            model_name='carcomplaints',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.complaints'),
        ),
        migrations.AddField(
            model_name='carcomplaints',
            name='complaints',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.car'),
        ),
        migrations.AddField(
            model_name='car',
            name='drive_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.driveaxlemodel', verbose_name='Модель вед. моста'),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.enginemodel', verbose_name='Модель двигателя'),
        ),
        migrations.AddField(
            model_name='car',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AddField(
            model_name='car',
            name='steerable_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.steerableaxlemodel', verbose_name='Модель упр. моста'),
        ),
        migrations.AddField(
            model_name='car',
            name='technique_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.techniquemodel', verbose_name='Модель техники'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.transmissionmodel', verbose_name='Модель трансмиссии'),
        ),
    ]
